apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rvs-app-ingress
spec:
  rules:
    - host: node-5.hse.rvc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rvs-app-service
                port:
                  number: 80